#!/bin/sh
# exec sh /etc/X11/xinit/xinitrc
#gnome-panel &
#gnome-settings-daemon &
#metacity &
#nautilus -n &

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
gnome-terminal &
gnome-session --session=ubuntu-2d
